services:
  db:
      image: mysql:8
      container_name: gr2_db
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: hung1234
        MYSQL_DATABASE: gr2_hust
      ports:
        - "3307:3306"
      volumes:
        - gr2_db_data:/var/lib/mysql

volumes:
  gr2_db_data: